-- Update recipes with CSV 'Analisi per porzione' values
-- Updates: total_calories, total_weight_g, and calories_per_100g
-- Generated automatically from Ricette PARTE1.csv

-- Add columns if they don't exist
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS total_weight_g DECIMAL(10,2);
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS calories_per_100g INTEGER;

DO $$
BEGIN
  RAISE NOTICE 'Updating recipes with CSV values (calories, weight, calories_per_100g)...';

  UPDATE recipes SET total_calories = 146, total_weight_g = 150.0, calories_per_100g = 97 WHERE LOWER(title) = LOWER('Affogato al caffè con due palline di fiordilatte');
  UPDATE recipes SET total_calories = 138, total_weight_g = 169.3, calories_per_100g = 81 WHERE LOWER(title) = LOWER('Alici marinate');
  UPDATE recipes SET total_calories = 213, total_weight_g = 102.3, calories_per_100g = 208 WHERE LOWER(title) = LOWER('Arrosticini di agnello');
  UPDATE recipes SET total_calories = 127, total_weight_g = 163.0, calories_per_100g = 77 WHERE LOWER(title) = LOWER('Arrosto di vitello');
  UPDATE recipes SET total_calories = 74, total_weight_g = 210.3, calories_per_100g = 35 WHERE LOWER(title) = LOWER('Asparagi lessati e conditi');
  UPDATE recipes SET total_calories = 77, total_weight_g = 160.0, calories_per_100g = 48 WHERE LOWER(title) = LOWER('Banana zucchero e limone');
  UPDATE recipes SET total_calories = 142, total_weight_g = 101.8, calories_per_100g = 139 WHERE LOWER(title) = LOWER('Besciamella');
  UPDATE recipes SET total_calories = 439, total_weight_g = 16.51, calories_per_100g = 2658 WHERE LOWER(title) = LOWER('Biscotto frollino');
  UPDATE recipes SET total_calories = 113, total_weight_g = 191.5, calories_per_100g = 59 WHERE LOWER(title) = LOWER('Bistecca alla pizzaiola');
  UPDATE recipes SET total_calories = 211, total_weight_g = 112.4, calories_per_100g = 187 WHERE LOWER(title) = LOWER('Bistecca di cavallo ai ferri');
  UPDATE recipes SET total_calories = 178, total_weight_g = 112.4, calories_per_100g = 158 WHERE LOWER(title) = LOWER('Bistecca di manzo ai ferri');
  UPDATE recipes SET total_calories = 177, total_weight_g = 112.0, calories_per_100g = 158 WHERE LOWER(title) = LOWER('Bollito magro a cubettini freddo con extravergine');
  UPDATE recipes SET total_calories = 168, total_weight_g = 100.3, calories_per_100g = 167 WHERE LOWER(title) = LOWER('Bollito misto');
  UPDATE recipes SET total_calories = 106, total_weight_g = 100.3, calories_per_100g = 105 WHERE LOWER(title) = LOWER('Bollito, tagli magri');
  UPDATE recipes SET total_calories = 103, total_weight_g = 161.5, calories_per_100g = 63 WHERE LOWER(title) = LOWER('Brasato');
  UPDATE recipes SET total_calories = 217, total_weight_g = 97.0, calories_per_100g = 223 WHERE LOWER(title) = LOWER('Bresaola condita (pomodorini, rucola, scaglie di grana, limone e olio)');
  UPDATE recipes SET total_calories = 74, total_weight_g = 210.3, calories_per_100g = 35 WHERE LOWER(title) = LOWER('Broccoli lessati o al vapore, conditi con extravergine');
  UPDATE recipes SET total_calories = 378, total_weight_g = 61.3, calories_per_100g = 616 WHERE LOWER(title) = LOWER('Bruschetta');
  UPDATE recipes SET total_calories = 37, total_weight_g = 155.0, calories_per_100g = 23 WHERE LOWER(title) = LOWER('Caffelatte (parz. screm.)');
  UPDATE recipes SET total_calories = 61, total_weight_g = 45.0, calories_per_100g = 135 WHERE LOWER(title) = LOWER('Caffè "marocchino"');
  UPDATE recipes SET total_calories = 15, total_weight_g = 38.0, calories_per_100g = 39 WHERE LOWER(title) = LOWER('Caffè macchiato');
  UPDATE recipes SET total_calories = 49, total_weight_g = 165.0, calories_per_100g = 29 WHERE LOWER(title) = LOWER('Cappuccino senza zucchero');
  UPDATE recipes SET total_calories = 122, total_weight_g = 312.4, calories_per_100g = 39 WHERE LOWER(title) = LOWER('Caprese');
  UPDATE recipes SET total_calories = 73, total_weight_g = 218.3, calories_per_100g = 33 WHERE LOWER(title) = LOWER('Carciofi in padella con aglio e prezzemolo');
  UPDATE recipes SET total_calories = 74, total_weight_g = 210.3, calories_per_100g = 35 WHERE LOWER(title) = LOWER('Carciofi, in pinzimonio');
  UPDATE recipes SET total_calories = 78, total_weight_g = 215.3, calories_per_100g = 36 WHERE LOWER(title) = LOWER('Carote alla julienne, con olio e limone');
  UPDATE recipes SET total_calories = 80, total_weight_g = 210.3, calories_per_100g = 38 WHERE LOWER(title) = LOWER('Carote lessate o al vapore, con extravergine');
  UPDATE recipes SET total_calories = 191, total_weight_g = 135.4, calories_per_100g = 141 WHERE LOWER(title) = LOWER('Carpaccio di manzo condito con scaglie di parmigiano e rucola');
  UPDATE recipes SET total_calories = 147, total_weight_g = 174.4, calories_per_100g = 84 WHERE LOWER(title) = LOWER('Carpaccio di pesce spada, condito');
  UPDATE recipes SET total_calories = 124, total_weight_g = 174.4, calories_per_100g = 71 WHERE LOWER(title) = LOWER('Carpaccio di spigola o branzino, condito');
  UPDATE recipes SET total_calories = 71, total_weight_g = 210.3, calories_per_100g = 33 WHERE LOWER(title) = LOWER('Cavolfiore lessato o al vapore, con extravergine');
  UPDATE recipes SET total_calories = 88, total_weight_g = 210.3, calories_per_100g = 41 WHERE LOWER(title) = LOWER('Cavolini di Bruxelles lessati o al vapore, con extravergine');
  UPDATE recipes SET total_calories = 113, total_weight_g = 95.4, calories_per_100g = 118 WHERE LOWER(title) = LOWER('Cavolo cappuccio in insalata, tagliato finemente, con extravergne');
  UPDATE recipes SET total_calories = 213, total_weight_g = 150.4, calories_per_100g = 141 WHERE LOWER(title) = LOWER('Ceci in umido con sugo al pomodoro');
  UPDATE recipes SET total_calories = 71, total_weight_g = 210.4, calories_per_100g = 33 WHERE LOWER(title) = LOWER('Cicoria o catalogna cotta e condita');
  UPDATE recipes SET total_calories = 105, total_weight_g = 143.0, calories_per_100g = 73 WHERE LOWER(title) = LOWER('Cioccolata calda');
  UPDATE recipes SET total_calories = 70, total_weight_g = 211.4, calories_per_100g = 33 WHERE LOWER(title) = LOWER('Cipolle al forno');
  UPDATE recipes SET total_calories = 69, total_weight_g = 213.4, calories_per_100g = 32 WHERE LOWER(title) = LOWER('Cipolle lessate, condite con extravergine');
  UPDATE recipes SET total_calories = 224, total_weight_g = 117.4, calories_per_100g = 190 WHERE LOWER(title) = LOWER('Coniglio arrosto');
  UPDATE recipes SET total_calories = 194, total_weight_g = 111.3, calories_per_100g = 174 WHERE LOWER(title) = LOWER('Coscia di pollo arrosto (con pelle)');
  UPDATE recipes SET total_calories = 178, total_weight_g = 111.3, calories_per_100g = 159 WHERE LOWER(title) = LOWER('Coscia di pollo arrosto (senza pelle)');
  UPDATE recipes SET total_calories = 195, total_weight_g = 111.3, calories_per_100g = 175 WHERE LOWER(title) = LOWER('Coscia di tacchino al forno');
  UPDATE recipes SET total_calories = 61, total_weight_g = 210.3, calories_per_100g = 29 WHERE LOWER(title) = LOWER('Coste o biete lessate con extravergine');
  UPDATE recipes SET total_calories = 267, total_weight_g = 100.3, calories_per_100g = 266 WHERE LOWER(title) = LOWER('Costine di maiale ai ferri');
  UPDATE recipes SET total_calories = 186, total_weight_g = 153.3, calories_per_100g = 121 WHERE LOWER(title) = LOWER('Cotoletta alla milanese');
  UPDATE recipes SET total_calories = 133, total_weight_g = 215.1, calories_per_100g = 61 WHERE LOWER(title) = LOWER('Crema di ceci');
  UPDATE recipes SET total_calories = 129, total_weight_g = 215.1, calories_per_100g = 59 WHERE LOWER(title) = LOWER('Crema di fagioli cannellini');
  UPDATE recipes SET total_calories = 72, total_weight_g = 320.6, calories_per_100g = 22 WHERE LOWER(title) = LOWER('Crema di piselli');
  UPDATE recipes SET total_calories = 73, total_weight_g = 392.1, calories_per_100g = 18 WHERE LOWER(title) = LOWER('Crema di piselli con patate');
  UPDATE recipes SET total_calories = 44, total_weight_g = 372.1, calories_per_100g = 11 WHERE LOWER(title) = LOWER('Crema di zucca');
  UPDATE recipes SET total_calories = 68, total_weight_g = 473.1, calories_per_100g = 14 WHERE LOWER(title) = LOWER('Crema porri e patate');
  UPDATE recipes SET total_calories = 359, total_weight_g = 100.0, calories_per_100g = 359 WHERE LOWER(title) = LOWER('Crostata alla marmellata');
  UPDATE recipes SET total_calories = 213, total_weight_g = 137.4, calories_per_100g = 155 WHERE LOWER(title) = LOWER('Fagioli all''uccelletto');
  UPDATE recipes SET total_calories = 277, total_weight_g = 110.0, calories_per_100g = 251 WHERE LOWER(title) = LOWER('Fagioli con nervetti');
  UPDATE recipes SET total_calories = 199, total_weight_g = 147.4, calories_per_100g = 135 WHERE LOWER(title) = LOWER('Fagioli in umido con sugo al pomodoro');
  UPDATE recipes SET total_calories = 54, total_weight_g = 267.0, calories_per_100g = 20 WHERE LOWER(title) = LOWER('Fagiolini in padella');
  UPDATE recipes SET total_calories = 66, total_weight_g = 210.4, calories_per_100g = 31 WHERE LOWER(title) = LOWER('Fagiolini lessati e conditi');
  UPDATE recipes SET total_calories = 412, total_weight_g = 90.3, calories_per_100g = 456 WHERE LOWER(title) = LOWER('Farro bollito condito con extravergine');
  UPDATE recipes SET total_calories = 158, total_weight_g = 154.4, calories_per_100g = 102 WHERE LOWER(title) = LOWER('Fegato alla veneta');
  UPDATE recipes SET total_calories = 78, total_weight_g = 348.4, calories_per_100g = 22 WHERE LOWER(title) = LOWER('Filetti di merluzzo con pomodori, olive e capperi');
  UPDATE recipes SET total_calories = 197, total_weight_g = 110.4, calories_per_100g = 178 WHERE LOWER(title) = LOWER('Filetto di manzo ai ferri');
  UPDATE recipes SET total_calories = 65, total_weight_g = 240.3, calories_per_100g = 27 WHERE LOWER(title) = LOWER('Finocchi gratinati');
  UPDATE recipes SET total_calories = 55, total_weight_g = 210.4, calories_per_100g = 26 WHERE LOWER(title) = LOWER('Finocchi in insalata');
  UPDATE recipes SET total_calories = 61, total_weight_g = 210.4, calories_per_100g = 28 WHERE LOWER(title) = LOWER('Finocchi in insalata con arance');
  UPDATE recipes SET total_calories = 55, total_weight_g = 212.3, calories_per_100g = 25 WHERE LOWER(title) = LOWER('Finocchi in padella');
  UPDATE recipes SET total_calories = 105, total_weight_g = 250.0, calories_per_100g = 42 WHERE LOWER(title) = LOWER('Fragole con gelato fiordilatte');
  UPDATE recipes SET total_calories = 41, total_weight_g = 160.0, calories_per_100g = 25 WHERE LOWER(title) = LOWER('Fragole zucchero e limone');
  UPDATE recipes SET total_calories = 213, total_weight_g = 60.15, calories_per_100g = 354 WHERE LOWER(title) = LOWER('Frittata');
  UPDATE recipes SET total_calories = 142, total_weight_g = 100.15, calories_per_100g = 141 WHERE LOWER(title) = LOWER('Frittata con porri');
  UPDATE recipes SET total_calories = 67, total_weight_g = 216.3, calories_per_100g = 30 WHERE LOWER(title) = LOWER('Funghi misti trifolati');
  UPDATE recipes SET total_calories = 218, total_weight_g = 100.0, calories_per_100g = 218 WHERE LOWER(title) = LOWER('Gelato alle creme');
  UPDATE recipes SET total_calories = 236, total_weight_g = 235.4, calories_per_100g = 100 WHERE LOWER(title) = LOWER('Gnocchi di patate al gorgonzola');
  UPDATE recipes SET total_calories = 207, total_weight_g = 180.0, calories_per_100g = 114 WHERE LOWER(title) = LOWER('Gnocchi di patate al pesto');
  UPDATE recipes SET total_calories = 143, total_weight_g = 230.3, calories_per_100g = 62 WHERE LOWER(title) = LOWER('Gnocchi di patate al pomodoro');
  UPDATE recipes SET total_calories = 133, total_weight_g = 320.4, calories_per_100g = 41 WHERE LOWER(title) = LOWER('Gnocchi di patate al ragù');
  UPDATE recipes SET total_calories = 169, total_weight_g = 170.3, calories_per_100g = 99 WHERE LOWER(title) = LOWER('Gnocchi di patate con burro e salvia');
  UPDATE recipes SET total_calories = 176, total_weight_g = 165.3, calories_per_100g = 106 WHERE LOWER(title) = LOWER('Gnocchi di patate olio e parmigiano');
  UPDATE recipes SET total_calories = 222, total_weight_g = 110.3, calories_per_100g = 201 WHERE LOWER(title) = LOWER('Hamburger di manzo da polpa scelta');
  UPDATE recipes SET total_calories = 147, total_weight_g = 170.0, calories_per_100g = 86 WHERE LOWER(title) = LOWER('Insalata di baccalà con prezzemolo e olive');
  UPDATE recipes SET total_calories = 179, total_weight_g = 162.3, calories_per_100g = 110 WHERE LOWER(title) = LOWER('Insalata di fagioli con cipolle');
  UPDATE recipes SET total_calories = 148, total_weight_g = 198.3, calories_per_100g = 74 WHERE LOWER(title) = LOWER('Insalata di fagioli e pomodori');
  UPDATE recipes SET total_calories = 204, total_weight_g = 193.3, calories_per_100g = 105 WHERE LOWER(title) = LOWER('Insalata di farro con verdure a cubetti saltate o grigliate');
  UPDATE recipes SET total_calories = 189, total_weight_g = 210.3, calories_per_100g = 89 WHERE LOWER(title) = LOWER('Insalata di farro riso e orzo con dadini di verdure');
  UPDATE recipes SET total_calories = 293, total_weight_g = 145.3, calories_per_100g = 201 WHERE LOWER(title) = LOWER('Insalata di farro riso e orzo con piselli e olio a crudo');
  UPDATE recipes SET total_calories = 118, total_weight_g = 168.0, calories_per_100g = 70 WHERE LOWER(title) = LOWER('Insalata di gamberetti con olio, prezzemolo e limone');
  UPDATE recipes SET total_calories = 104, total_weight_g = 194.0, calories_per_100g = 53 WHERE LOWER(title) = LOWER('Insalata di mare');
  UPDATE recipes SET total_calories = 92, total_weight_g = 367.4, calories_per_100g = 25 WHERE LOWER(title) = LOWER('Insalata di polpo con patate');
  UPDATE recipes SET total_calories = 208, total_weight_g = 245.3, calories_per_100g = 84 WHERE LOWER(title) = LOWER('Insalata di riso');
  UPDATE recipes SET total_calories = 424, total_weight_g = 64.4, calories_per_100g = 658 WHERE LOWER(title) = LOWER('Insalata fredda di ceci con extravergine');
  UPDATE recipes SET total_calories = 211, total_weight_g = 160.4, calories_per_100g = 131 WHERE LOWER(title) = LOWER('Insalata fredda di ceci con peperonata');
  UPDATE recipes SET total_calories = 69, total_weight_g = 195.3, calories_per_100g = 35 WHERE LOWER(title) = LOWER('Insalata mista con carote e pomodori, condita');
  UPDATE recipes SET total_calories = 110, total_weight_g = 95.3, calories_per_100g = 115 WHERE LOWER(title) = LOWER('Insalata, condita');
  UPDATE recipes SET total_calories = 133, total_weight_g = 225.4, calories_per_100g = 59 WHERE LOWER(title) = LOWER('Involtini di carne con spinaci');
  UPDATE recipes SET total_calories = 201, total_weight_g = 150.4, calories_per_100g = 133 WHERE LOWER(title) = LOWER('Involtini di pollo con prosciutto e formaggio');
  UPDATE recipes SET total_calories = 149, total_weight_g = 250.0, calories_per_100g = 59 WHERE LOWER(title) = LOWER('Lasagne alla bolognese');
  UPDATE recipes SET total_calories = 52, total_weight_g = 155.0, calories_per_100g = 33 WHERE LOWER(title) = LOWER('Latte macchiato');
  UPDATE recipes SET total_calories = 113, total_weight_g = 95.3, calories_per_100g = 118 WHERE LOWER(title) = LOWER('Lattuga, condita');
  UPDATE recipes SET total_calories = 194, total_weight_g = 153.7, calories_per_100g = 126 WHERE LOWER(title) = LOWER('Lenticchie in umido con sugo al pomodoro');
  UPDATE recipes SET total_calories = 221, total_weight_g = 112.4, calories_per_100g = 196 WHERE LOWER(title) = LOWER('Lonza di maiale in padella');
  UPDATE recipes SET total_calories = 66, total_weight_g = 160.0, calories_per_100g = 41 WHERE LOWER(title) = LOWER('Macedonia');
  UPDATE recipes SET total_calories = 122, total_weight_g = 250.0, calories_per_100g = 48 WHERE LOWER(title) = LOWER('Macedonia con due palline di gelato');
  UPDATE recipes SET total_calories = 58, total_weight_g = 157.0, calories_per_100g = 36 WHERE LOWER(title) = LOWER('Mela cotta con cannella');
  UPDATE recipes SET total_calories = 54, total_weight_g = 300.3, calories_per_100g = 17 WHERE LOWER(title) = LOWER('Melanzane al pomodoro');
  UPDATE recipes SET total_calories = 62, total_weight_g = 212.3, calories_per_100g = 29 WHERE LOWER(title) = LOWER('Melanzane grigliate');
  UPDATE recipes SET total_calories = 157, total_weight_g = 337.3, calories_per_100g = 46 WHERE LOWER(title) = LOWER('Melanzane in carrozza');
  UPDATE recipes SET total_calories = 121, total_weight_g = 163.3, calories_per_100g = 74 WHERE LOWER(title) = LOWER('Merluzzo al vapore con olio');
  UPDATE recipes SET total_calories = 55, total_weight_g = 444.1, calories_per_100g = 12 WHERE LOWER(title) = LOWER('Minestrone di verdure con patate e legumi');
  UPDATE recipes SET total_calories = 49, total_weight_g = 344.1, calories_per_100g = 14 WHERE LOWER(title) = LOWER('Minestrone di verdure senza patate e legumi');
  UPDATE recipes SET total_calories = 85, total_weight_g = 344.1, calories_per_100g = 24 WHERE LOWER(title) = LOWER('Minestrone di verdure senza patate e legumi con orzo');
  UPDATE recipes SET total_calories = 88, total_weight_g = 344.1, calories_per_100g = 25 WHERE LOWER(title) = LOWER('Minestrone di verdure senza patate e legumi con pastina');
  UPDATE recipes SET total_calories = 88, total_weight_g = 344.1, calories_per_100g = 25 WHERE LOWER(title) = LOWER('Minestrone di verdure senza patate e legumi con riso');
  UPDATE recipes SET total_calories = 85, total_weight_g = 100.0, calories_per_100g = 85 WHERE LOWER(title) = LOWER('Nervetti a cubetti');
  UPDATE recipes SET total_calories = 165, total_weight_g = 110.4, calories_per_100g = 149 WHERE LOWER(title) = LOWER('Nodino di vitello ai ferri');
  UPDATE recipes SET total_calories = 205, total_weight_g = 160.3, calories_per_100g = 127 WHERE LOWER(title) = LOWER('Orata al forno, sfilettata');
  UPDATE recipes SET total_calories = 178, total_weight_g = 247.4, calories_per_100g = 71 WHERE LOWER(title) = LOWER('Orecchiette con i broccoli');
  UPDATE recipes SET total_calories = 62, total_weight_g = 215.3, calories_per_100g = 28 WHERE LOWER(title) = LOWER('Ortaggi misti, conditi');
  UPDATE recipes SET total_calories = 398, total_weight_g = 90.3, calories_per_100g = 440 WHERE LOWER(title) = LOWER('Orzo bollito con olio a crudo');
  UPDATE recipes SET total_calories = 141, total_weight_g = 195.1, calories_per_100g = 72 WHERE LOWER(title) = LOWER('Pancotto bianco');
  UPDATE recipes SET total_calories = 203, total_weight_g = 143.4, calories_per_100g = 141 WHERE LOWER(title) = LOWER('Pancotto rosso');
  UPDATE recipes SET total_calories = 193, total_weight_g = 245.0, calories_per_100g = 78 WHERE LOWER(title) = LOWER('Panino con hamburger');
  UPDATE recipes SET total_calories = 260, total_weight_g = 75.0, calories_per_100g = 346 WHERE LOWER(title) = LOWER('Panino rosetta con prosciutto cotto');
  UPDATE recipes SET total_calories = 281, total_weight_g = 100.0, calories_per_100g = 281 WHERE LOWER(title) = LOWER('Panino rosetta con prosciutto cotto e fontina');
  UPDATE recipes SET total_calories = 316, total_weight_g = 75.0, calories_per_100g = 421 WHERE LOWER(title) = LOWER('Panino rosetta con salame');
  UPDATE recipes SET total_calories = 145, total_weight_g = 187.4, calories_per_100g = 77 WHERE LOWER(title) = LOWER('Panzanella');
  UPDATE recipes SET total_calories = 86, total_weight_g = 371.1, calories_per_100g = 23 WHERE LOWER(title) = LOWER('Pappa al pomodoro');
  UPDATE recipes SET total_calories = 132, total_weight_g = 409.4, calories_per_100g = 32 WHERE LOWER(title) = LOWER('Parmigiana di melanzane');
  UPDATE recipes SET total_calories = 49, total_weight_g = 343.1, calories_per_100g = 14 WHERE LOWER(title) = LOWER('Passato di verdure senza patate e legumi');

  RAISE NOTICE 'Updated % recipes', (SELECT COUNT(*) FROM recipes WHERE total_weight_g > 0);
END $$;
