-- Update recipes.total_calories with CSV 'Analisi per porzione' values
-- Generated automatically from Ricette PARTE1.csv

DO $$
BEGIN
  RAISE NOTICE 'Updating recipes with CSV calorie values...';

  UPDATE recipes SET total_calories = 146 WHERE LOWER(title) = LOWER('Affogato al caffè con due palline di fiordilatte');
  UPDATE recipes SET total_calories = 138 WHERE LOWER(title) = LOWER('Alici marinate');
  UPDATE recipes SET total_calories = 213 WHERE LOWER(title) = LOWER('Arrosticini di agnello');
  UPDATE recipes SET total_calories = 127 WHERE LOWER(title) = LOWER('Arrosto di vitello');
  UPDATE recipes SET total_calories = 74 WHERE LOWER(title) = LOWER('Asparagi lessati e conditi');
  UPDATE recipes SET total_calories = 77 WHERE LOWER(title) = LOWER('Banana zucchero e limone');
  UPDATE recipes SET total_calories = 142 WHERE LOWER(title) = LOWER('Besciamella');
  UPDATE recipes SET total_calories = 439 WHERE LOWER(title) = LOWER('Biscotto frollino');
  UPDATE recipes SET total_calories = 113 WHERE LOWER(title) = LOWER('Bistecca alla pizzaiola');
  UPDATE recipes SET total_calories = 211 WHERE LOWER(title) = LOWER('Bistecca di cavallo ai ferri');
  UPDATE recipes SET total_calories = 178 WHERE LOWER(title) = LOWER('Bistecca di manzo ai ferri');
  UPDATE recipes SET total_calories = 177 WHERE LOWER(title) = LOWER('Bollito magro a cubettini freddo con extravergine');
  UPDATE recipes SET total_calories = 168 WHERE LOWER(title) = LOWER('Bollito misto');
  UPDATE recipes SET total_calories = 106 WHERE LOWER(title) = LOWER('Bollito, tagli magri');
  UPDATE recipes SET total_calories = 103 WHERE LOWER(title) = LOWER('Brasato');
  UPDATE recipes SET total_calories = 217 WHERE LOWER(title) = LOWER('Bresaola condita (pomodorini, rucola, scaglie di grana, limone e olio)');
  UPDATE recipes SET total_calories = 74 WHERE LOWER(title) = LOWER('Broccoli lessati o al vapore, conditi con extravergine');
  UPDATE recipes SET total_calories = 378 WHERE LOWER(title) = LOWER('Bruschetta');
  UPDATE recipes SET total_calories = 37 WHERE LOWER(title) = LOWER('Caffelatte (parz. screm.)');
  UPDATE recipes SET total_calories = 61 WHERE LOWER(title) = LOWER('Caffè "marocchino"');
  UPDATE recipes SET total_calories = 15 WHERE LOWER(title) = LOWER('Caffè macchiato');
  UPDATE recipes SET total_calories = 49 WHERE LOWER(title) = LOWER('Cappuccino senza zucchero');
  UPDATE recipes SET total_calories = 122 WHERE LOWER(title) = LOWER('Caprese');
  UPDATE recipes SET total_calories = 73 WHERE LOWER(title) = LOWER('Carciofi in padella con aglio e prezzemolo');
  UPDATE recipes SET total_calories = 74 WHERE LOWER(title) = LOWER('Carciofi, in pinzimonio');
  UPDATE recipes SET total_calories = 78 WHERE LOWER(title) = LOWER('Carote alla julienne, con olio e limone');
  UPDATE recipes SET total_calories = 80 WHERE LOWER(title) = LOWER('Carote lessate o al vapore, con extravergine');
  UPDATE recipes SET total_calories = 191 WHERE LOWER(title) = LOWER('Carpaccio di manzo condito con scaglie di parmigiano e rucola');
  UPDATE recipes SET total_calories = 147 WHERE LOWER(title) = LOWER('Carpaccio di pesce spada, condito');
  UPDATE recipes SET total_calories = 124 WHERE LOWER(title) = LOWER('Carpaccio di spigola o branzino, condito');
  UPDATE recipes SET total_calories = 71 WHERE LOWER(title) = LOWER('Cavolfiore lessato o al vapore, con extravergine');
  UPDATE recipes SET total_calories = 88 WHERE LOWER(title) = LOWER('Cavolini di Bruxelles lessati o al vapore, con extravergine');
  UPDATE recipes SET total_calories = 113 WHERE LOWER(title) = LOWER('Cavolo cappuccio in insalata, tagliato finemente, con extravergne');
  UPDATE recipes SET total_calories = 213 WHERE LOWER(title) = LOWER('Ceci in umido con sugo al pomodoro');
  UPDATE recipes SET total_calories = 71 WHERE LOWER(title) = LOWER('Cicoria o catalogna cotta e condita');
  UPDATE recipes SET total_calories = 105 WHERE LOWER(title) = LOWER('Cioccolata calda');
  UPDATE recipes SET total_calories = 70 WHERE LOWER(title) = LOWER('Cipolle al forno');
  UPDATE recipes SET total_calories = 69 WHERE LOWER(title) = LOWER('Cipolle lessate, condite con extravergine');
  UPDATE recipes SET total_calories = 224 WHERE LOWER(title) = LOWER('Coniglio arrosto');
  UPDATE recipes SET total_calories = 194 WHERE LOWER(title) = LOWER('Coscia di pollo arrosto (con pelle)');
  UPDATE recipes SET total_calories = 178 WHERE LOWER(title) = LOWER('Coscia di pollo arrosto (senza pelle)');
  UPDATE recipes SET total_calories = 195 WHERE LOWER(title) = LOWER('Coscia di tacchino al forno');
  UPDATE recipes SET total_calories = 61 WHERE LOWER(title) = LOWER('Coste o biete lessate con extravergine');
  UPDATE recipes SET total_calories = 267 WHERE LOWER(title) = LOWER('Costine di maiale ai ferri');
  UPDATE recipes SET total_calories = 186 WHERE LOWER(title) = LOWER('Cotoletta alla milanese');
  UPDATE recipes SET total_calories = 133 WHERE LOWER(title) = LOWER('Crema di ceci');
  UPDATE recipes SET total_calories = 129 WHERE LOWER(title) = LOWER('Crema di fagioli cannellini');
  UPDATE recipes SET total_calories = 72 WHERE LOWER(title) = LOWER('Crema di piselli');
  UPDATE recipes SET total_calories = 73 WHERE LOWER(title) = LOWER('Crema di piselli con patate');
  UPDATE recipes SET total_calories = 44 WHERE LOWER(title) = LOWER('Crema di zucca');
  UPDATE recipes SET total_calories = 68 WHERE LOWER(title) = LOWER('Crema porri e patate');
  UPDATE recipes SET total_calories = 359 WHERE LOWER(title) = LOWER('Crostata alla marmellata');
  UPDATE recipes SET total_calories = 213 WHERE LOWER(title) = LOWER('Fagioli all''uccelletto');
  UPDATE recipes SET total_calories = 277 WHERE LOWER(title) = LOWER('Fagioli con nervetti');
  UPDATE recipes SET total_calories = 199 WHERE LOWER(title) = LOWER('Fagioli in umido con sugo al pomodoro');
  UPDATE recipes SET total_calories = 54 WHERE LOWER(title) = LOWER('Fagiolini in padella');
  UPDATE recipes SET total_calories = 66 WHERE LOWER(title) = LOWER('Fagiolini lessati e conditi');
  UPDATE recipes SET total_calories = 412 WHERE LOWER(title) = LOWER('Farro bollito condito con extravergine');
  UPDATE recipes SET total_calories = 158 WHERE LOWER(title) = LOWER('Fegato alla veneta');
  UPDATE recipes SET total_calories = 78 WHERE LOWER(title) = LOWER('Filetti di merluzzo con pomodori, olive e capperi');
  UPDATE recipes SET total_calories = 197 WHERE LOWER(title) = LOWER('Filetto di manzo ai ferri');
  UPDATE recipes SET total_calories = 65 WHERE LOWER(title) = LOWER('Finocchi gratinati');
  UPDATE recipes SET total_calories = 55 WHERE LOWER(title) = LOWER('Finocchi in insalata');
  UPDATE recipes SET total_calories = 61 WHERE LOWER(title) = LOWER('Finocchi in insalata con arance');
  UPDATE recipes SET total_calories = 55 WHERE LOWER(title) = LOWER('Finocchi in padella');
  UPDATE recipes SET total_calories = 105 WHERE LOWER(title) = LOWER('Fragole con gelato fiordilatte');
  UPDATE recipes SET total_calories = 41 WHERE LOWER(title) = LOWER('Fragole zucchero e limone');
  UPDATE recipes SET total_calories = 213 WHERE LOWER(title) = LOWER('Frittata');
  UPDATE recipes SET total_calories = 142 WHERE LOWER(title) = LOWER('Frittata con porri');
  UPDATE recipes SET total_calories = 67 WHERE LOWER(title) = LOWER('Funghi misti trifolati');
  UPDATE recipes SET total_calories = 218 WHERE LOWER(title) = LOWER('Gelato alle creme');
  UPDATE recipes SET total_calories = 236 WHERE LOWER(title) = LOWER('Gnocchi di patate al gorgonzola');
  UPDATE recipes SET total_calories = 207 WHERE LOWER(title) = LOWER('Gnocchi di patate al pesto');
  UPDATE recipes SET total_calories = 143 WHERE LOWER(title) = LOWER('Gnocchi di patate al pomodoro');
  UPDATE recipes SET total_calories = 133 WHERE LOWER(title) = LOWER('Gnocchi di patate al ragù');
  UPDATE recipes SET total_calories = 169 WHERE LOWER(title) = LOWER('Gnocchi di patate con burro e salvia');
  UPDATE recipes SET total_calories = 176 WHERE LOWER(title) = LOWER('Gnocchi di patate olio e parmigiano');
  UPDATE recipes SET total_calories = 222 WHERE LOWER(title) = LOWER('Hamburger di manzo da polpa scelta');
  UPDATE recipes SET total_calories = 147 WHERE LOWER(title) = LOWER('Insalata di baccalà con prezzemolo e olive');
  UPDATE recipes SET total_calories = 179 WHERE LOWER(title) = LOWER('Insalata di fagioli con cipolle');
  UPDATE recipes SET total_calories = 148 WHERE LOWER(title) = LOWER('Insalata di fagioli e pomodori');
  UPDATE recipes SET total_calories = 204 WHERE LOWER(title) = LOWER('Insalata di farro con verdure a cubetti saltate o grigliate');
  UPDATE recipes SET total_calories = 189 WHERE LOWER(title) = LOWER('Insalata di farro riso e orzo con dadini di verdure');
  UPDATE recipes SET total_calories = 293 WHERE LOWER(title) = LOWER('Insalata di farro riso e orzo con piselli e olio a crudo');
  UPDATE recipes SET total_calories = 118 WHERE LOWER(title) = LOWER('Insalata di gamberetti con olio, prezzemolo e limone');
  UPDATE recipes SET total_calories = 104 WHERE LOWER(title) = LOWER('Insalata di mare');
  UPDATE recipes SET total_calories = 92 WHERE LOWER(title) = LOWER('Insalata di polpo con patate');
  UPDATE recipes SET total_calories = 208 WHERE LOWER(title) = LOWER('Insalata di riso');
  UPDATE recipes SET total_calories = 424 WHERE LOWER(title) = LOWER('Insalata fredda di ceci con extravergine');
  UPDATE recipes SET total_calories = 211 WHERE LOWER(title) = LOWER('Insalata fredda di ceci con peperonata');
  UPDATE recipes SET total_calories = 69 WHERE LOWER(title) = LOWER('Insalata mista con carote e pomodori, condita');
  UPDATE recipes SET total_calories = 110 WHERE LOWER(title) = LOWER('Insalata, condita');
  UPDATE recipes SET total_calories = 133 WHERE LOWER(title) = LOWER('Involtini di carne con spinaci');
  UPDATE recipes SET total_calories = 201 WHERE LOWER(title) = LOWER('Involtini di pollo con prosciutto e formaggio');
  UPDATE recipes SET total_calories = 149 WHERE LOWER(title) = LOWER('Lasagne alla bolognese');
  UPDATE recipes SET total_calories = 52 WHERE LOWER(title) = LOWER('Latte macchiato');
  UPDATE recipes SET total_calories = 113 WHERE LOWER(title) = LOWER('Lattuga, condita');
  UPDATE recipes SET total_calories = 194 WHERE LOWER(title) = LOWER('Lenticchie in umido con sugo al pomodoro');
  UPDATE recipes SET total_calories = 221 WHERE LOWER(title) = LOWER('Lonza di maiale in padella');
  UPDATE recipes SET total_calories = 66 WHERE LOWER(title) = LOWER('Macedonia');
  UPDATE recipes SET total_calories = 122 WHERE LOWER(title) = LOWER('Macedonia con due palline di gelato');
  UPDATE recipes SET total_calories = 58 WHERE LOWER(title) = LOWER('Mela cotta con cannella');
  UPDATE recipes SET total_calories = 54 WHERE LOWER(title) = LOWER('Melanzane al pomodoro');
  UPDATE recipes SET total_calories = 62 WHERE LOWER(title) = LOWER('Melanzane grigliate');
  UPDATE recipes SET total_calories = 157 WHERE LOWER(title) = LOWER('Melanzane in carrozza');
  UPDATE recipes SET total_calories = 121 WHERE LOWER(title) = LOWER('Merluzzo al vapore con olio');
  UPDATE recipes SET total_calories = 55 WHERE LOWER(title) = LOWER('Minestrone di verdure con patate e legumi');
  UPDATE recipes SET total_calories = 49 WHERE LOWER(title) = LOWER('Minestrone di verdure senza patate e legumi');
  UPDATE recipes SET total_calories = 85 WHERE LOWER(title) = LOWER('Minestrone di verdure senza patate e legumi con orzo');
  UPDATE recipes SET total_calories = 88 WHERE LOWER(title) = LOWER('Minestrone di verdure senza patate e legumi con pastina');
  UPDATE recipes SET total_calories = 88 WHERE LOWER(title) = LOWER('Minestrone di verdure senza patate e legumi con riso');
  UPDATE recipes SET total_calories = 85 WHERE LOWER(title) = LOWER('Nervetti a cubetti');
  UPDATE recipes SET total_calories = 165 WHERE LOWER(title) = LOWER('Nodino di vitello ai ferri');
  UPDATE recipes SET total_calories = 205 WHERE LOWER(title) = LOWER('Orata al forno, sfilettata');
  UPDATE recipes SET total_calories = 178 WHERE LOWER(title) = LOWER('Orecchiette con i broccoli');
  UPDATE recipes SET total_calories = 62 WHERE LOWER(title) = LOWER('Ortaggi misti, conditi');
  UPDATE recipes SET total_calories = 398 WHERE LOWER(title) = LOWER('Orzo bollito con olio a crudo');
  UPDATE recipes SET total_calories = 141 WHERE LOWER(title) = LOWER('Pancotto bianco');
  UPDATE recipes SET total_calories = 203 WHERE LOWER(title) = LOWER('Pancotto rosso');
  UPDATE recipes SET total_calories = 193 WHERE LOWER(title) = LOWER('Panino con hamburger');
  UPDATE recipes SET total_calories = 260 WHERE LOWER(title) = LOWER('Panino rosetta con prosciutto cotto');
  UPDATE recipes SET total_calories = 281 WHERE LOWER(title) = LOWER('Panino rosetta con prosciutto cotto e fontina');
  UPDATE recipes SET total_calories = 316 WHERE LOWER(title) = LOWER('Panino rosetta con salame');
  UPDATE recipes SET total_calories = 145 WHERE LOWER(title) = LOWER('Panzanella');
  UPDATE recipes SET total_calories = 86 WHERE LOWER(title) = LOWER('Pappa al pomodoro');
  UPDATE recipes SET total_calories = 132 WHERE LOWER(title) = LOWER('Parmigiana di melanzane');
  UPDATE recipes SET total_calories = 49 WHERE LOWER(title) = LOWER('Passato di verdure senza patate e legumi');

  RAISE NOTICE 'Updated % recipes', (SELECT COUNT(*) FROM recipes WHERE total_calories > 0);
END $$;
