-- Migration: Add BATCH 4 (Root Vegetables) + BATCH 5 (Cabbages) Foods to Database
-- Date: 2025-12-23 14:00:00
-- Description: Adding 8 new foods - 5 root vegetables (category 2003) and 3 cabbages/leafy vegetables (category 2004)

-- BATCH 4 - ROOT VEGETABLES (Category 2003)

-- FOOD 11: BEETROOT
INSERT INTO public.food_items (
    id,
    name,
    food_code,
    italian_name,
    english_name,
    scientific_name,
    category,
    edible_portion_percent,
    calories_per_100g,
    energy_kj,
    protein_per_100g,
    carbs_per_100g,
    fat_per_100g,
    fiber_per_100g,
    water_g,
    iron_mg,
    calcium_mg,
    sodium_per_100g,
    potassium_mg,
    phosphorus_mg,
    zinc_mg,
    vitamin_c_mg,
    is_verified,
    created_at
) VALUES (
    gen_random_uuid(),
    'BARBABIETOLE ROSSE',
    '306_1',
    'BARBABIETOLE ROSSE',
    'BEETROOT',
    'Beta vulgaris, cv rapa, forma rubra',
    '2003'::public.food_category_code,
    82,
    25,
    104,
    1.1,
    4.0,
    0.0,
    2.6,
    91.3,
    0.4,
    20,
    84,
    300,
    21,
    0.4,
    7,
    true,
    CURRENT_TIMESTAMP
);

-- FOOD 12: CARROTS
INSERT INTO public.food_items (
    id,
    name,
    food_code,
    italian_name,
    english_name,
    scientific_name,
    category,
    edible_portion_percent,
    calories_per_100g,
    energy_kj,
    protein_per_100g,
    carbs_per_100g,
    fat_per_100g,
    fiber_per_100g,
    water_g,
    iron_mg,
    calcium_mg,
    sodium_per_100g,
    potassium_mg,
    phosphorus_mg,
    zinc_mg,
    vitamin_c_mg,
    vitamin_a_mcg,
    is_verified,
    created_at
) VALUES (
    gen_random_uuid(),
    'CAROTE',
    '312_1',
    'CAROTE',
    'CARROTS',
    'Daucus carota',
    '2003'::public.food_category_code,
    95,
    39,
    165,
    1.1,
    7.6,
    0.0,
    3.1,
    91.6,
    0.7,
    44,
    95,
    220,
    37,
    0.4,
    4,
    1148,
    true,
    CURRENT_TIMESTAMP
);

-- FOOD 13: TURNIP
INSERT INTO public.food_items (
    id,
    name,
    food_code,
    italian_name,
    english_name,
    scientific_name,
    category,
    edible_portion_percent,
    calories_per_100g,
    energy_kj,
    protein_per_100g,
    carbs_per_100g,
    fat_per_100g,
    fiber_per_100g,
    water_g,
    iron_mg,
    calcium_mg,
    sodium_per_100g,
    potassium_mg,
    phosphorus_mg,
    zinc_mg,
    vitamin_c_mg,
    is_verified,
    created_at
) VALUES (
    gen_random_uuid(),
    'RAPE',
    '341_1',
    'RAPE',
    'TURNIP',
    'Brassica rapa',
    '2003'::public.food_category_code,
    69,
    23,
    99,
    1.0,
    3.8,
    0.0,
    2.6,
    93.3,
    0.6,
    40,
    58,
    240,
    29,
    0.08,
    23,
    true,
    CURRENT_TIMESTAMP
);

-- FOOD 14: RED RADISH
INSERT INTO public.food_items (
    id,
    name,
    food_code,
    italian_name,
    english_name,
    scientific_name,
    category,
    edible_portion_percent,
    calories_per_100g,
    energy_kj,
    protein_per_100g,
    carbs_per_100g,
    fat_per_100g,
    fiber_per_100g,
    water_g,
    iron_mg,
    calcium_mg,
    sodium_per_100g,
    potassium_mg,
    phosphorus_mg,
    zinc_mg,
    vitamin_c_mg,
    is_verified,
    created_at
) VALUES (
    gen_random_uuid(),
    'RAVANELLI',
    '342_1',
    'RAVANELLI',
    'RED RADISH',
    'Raphanus sativus',
    '2003'::public.food_category_code,
    99,
    13,
    56,
    0.8,
    1.8,
    0.1,
    1.3,
    95.6,
    0.9,
    39,
    59,
    240,
    29,
    0.09,
    18,
    true,
    CURRENT_TIMESTAMP
);

-- FOOD 15: CELERIAC
INSERT INTO public.food_items (
    id,
    name,
    food_code,
    italian_name,
    english_name,
    scientific_name,
    category,
    edible_portion_percent,
    calories_per_100g,
    energy_kj,
    protein_per_100g,
    carbs_per_100g,
    fat_per_100g,
    fiber_per_100g,
    water_g,
    iron_mg,
    calcium_mg,
    sodium_per_100g,
    potassium_mg,
    phosphorus_mg,
    zinc_mg,
    vitamin_c_mg,
    is_verified,
    created_at
) VALUES (
    gen_random_uuid(),
    'SEDANO RAPA',
    '344_1',
    'SEDANO RAPA',
    'CELERIAC',
    'Apium graveolens, cv rapaceum',
    '2003'::public.food_category_code,
    72,
    33,
    138,
    1.9,
    3.8,
    0.1,
    5.1,
    88.0,
    0.5,
    52,
    91,
    460,
    90,
    0.3,
    6,
    true,
    CURRENT_TIMESTAMP
);

-- BATCH 5 - CABBAGES & LEAFY VEGETABLES (Category 2004)

-- FOOD 16: TURNIP TOPS
INSERT INTO public.food_items (
    id,
    name,
    food_code,
    italian_name,
    english_name,
    scientific_name,
    category,
    edible_portion_percent,
    calories_per_100g,
    energy_kj,
    protein_per_100g,
    carbs_per_100g,
    fat_per_100g,
    fiber_per_100g,
    water_g,
    iron_mg,
    calcium_mg,
    sodium_per_100g,
    potassium_mg,
    phosphorus_mg,
    zinc_mg,
    vitamin_c_mg,
    is_verified,
    created_at
) VALUES (
    gen_random_uuid(),
    'BROCCOLETTI DI RAPE',
    '308_1',
    'BROCCOLETTI DI RAPE',
    'TURNIP TOPS',
    'Brassica rapa, cv esculenta',
    '2004'::public.food_category_code,
    60,
    28,
    116,
    2.9,
    2.0,
    0.3,
    2.9,
    90.7,
    1.5,
    97,
    7,
    296,
    69,
    0.2,
    110,
    true,
    CURRENT_TIMESTAMP
);

-- FOOD 17: BROCCOLI, PURPLE SPROUTING
INSERT INTO public.food_items (
    id,
    name,
    food_code,
    italian_name,
    english_name,
    scientific_name,
    category,
    edible_portion_percent,
    calories_per_100g,
    energy_kj,
    protein_per_100g,
    carbs_per_100g,
    fat_per_100g,
    fiber_per_100g,
    water_g,
    iron_mg,
    calcium_mg,
    sodium_per_100g,
    potassium_mg,
    phosphorus_mg,
    zinc_mg,
    vitamin_c_mg,
    is_verified,
    created_at
) VALUES (
    gen_random_uuid(),
    'BROCCOLO A TESTA',
    '309_1',
    'BROCCOLO A TESTA',
    'BROCCOLI, PURPLE SPROUTING',
    'Brassica oleracea, cv botrytis caput',
    '2004'::public.food_category_code,
    51,
    33,
    140,
    3.0,
    3.1,
    0.4,
    3.1,
    90.3,
    0.8,
    28,
    12,
    340,
    66,
    0.6,
    54,
    true,
    CURRENT_TIMESTAMP
);

-- FOOD 18: CAULIFLOWER
INSERT INTO public.food_items (
    id,
    name,
    food_code,
    italian_name,
    english_name,
    scientific_name,
    category,
    edible_portion_percent,
    calories_per_100g,
    energy_kj,
    protein_per_100g,
    carbs_per_100g,
    fat_per_100g,
    fiber_per_100g,
    water_g,
    iron_mg,
    calcium_mg,
    sodium_per_100g,
    potassium_mg,
    phosphorus_mg,
    zinc_mg,
    vitamin_c_mg,
    is_verified,
    created_at
) VALUES (
    gen_random_uuid(),
    'CAVOLFIORE',
    '313_1',
    'CAVOLFIORE',
    'CAULIFLOWER',
    'Brassica oleracea, cv botrytis cauliflaura',
    '2004'::public.food_category_code,
    66,
    30,
    124,
    3.2,
    2.7,
    0.2,
    2.4,
    90.5,
    0.8,
    44,
    8,
    350,
    69,
    0.7,
    59,
    true,
    CURRENT_TIMESTAMP
);

-- Update search vectors for all new foods (handled automatically by triggers)
-- Verify food category enum values are supported
DO $$
BEGIN
    -- Verify that the food categories exist
    IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel IN ('2003', '2004') AND enumtypid = 'public.food_category_code'::regtype) THEN
        RAISE EXCEPTION 'Food category codes 2003 or 2004 not found in food_category_code enum';
    END IF;
    
    RAISE NOTICE 'Successfully added 8 new foods: 5 root vegetables (category 2003) and 3 cabbages/leafy vegetables (category 2004)';
END $$;